import React, { useEffect, useState } from 'react';
import { Copy } from 'lucide-react';
import { api, authHeaders, Empty, LoadingButton, NetworkError, Panel } from './shared';
import type { PushToast } from './shared';

export default function AssetsPanel({ push }: { push: PushToast }) { const [assets, setAssets] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { setError(''); const d = await api('/api/assets'); setAssets(d.assets || []); } catch (e:any) { setError(e.message); push('error', e.message);} };
  useEffect(() => { load(); }, []);
  async function upload(files: FileList | null) { if (!files?.length || loading) return; setLoading(true); try { for (const file of Array.from(files)) { const form = new FormData(); form.append('file', file); await api('/api/assets/upload', { method: 'POST', headers: authHeaders(), body: form }); } await load(); push('success', `上传成功 (${files.length})`); } catch (e: any) { push('error', `上传失败: ${e.message}`); } finally { setLoading(false); } }
  return <Panel title='资源管理'>{error && <NetworkError message={error} onRetry={load} />}<label className='flex min-h-36 cursor-pointer items-center justify-center rounded-2xl border border-dashed border-[var(--border)] p-6 text-sm text-[var(--muted)]'>{loading ? '上传中...' : '点击选择图片上传（可多选）'}<input multiple type='file' accept='image/*' className='hidden' onChange={(e) => upload(e.target.files)} /></label>{!assets.length ? <Empty label='暂无资源' /> : <div className='mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-4'>{assets.map((asset) => <div key={asset.id} className='rounded-xl border border-[var(--border)] p-3'><img src={asset.public_url} alt={asset.original_filename} className='h-28 w-full rounded-lg object-cover' /><div className='mt-2 truncate text-xs'>{asset.original_filename}</div><LoadingButton loading={false} className='mt-2 rounded border px-2 py-1 text-xs' onClick={async () => { await navigator.clipboard.writeText(`![${asset.original_filename}](${asset.public_url})`); push('success', 'Markdown 已复制'); }}><Copy size={12} className='mr-1 inline' />Markdown</LoadingButton></div>)}</div>}</Panel>; }
