import React, { useEffect, useState } from 'react';
import CodeMirror from '@uiw/react-codemirror';
import { markdown } from '@codemirror/lang-markdown';
import { Plus, Save, Send, Trash2 } from 'lucide-react';
import { api, Empty, LoadingButton, NetworkError } from './shared';
import type { PushToast } from './shared';

type PageItem = { id: string; title: string; slug: string; status: string; summary?: string; content?: string; meta_title?: string; meta_description?: string };

export default function PagesPanel({ push }: { push: PushToast }) { const [pages, setPages] = useState<PageItem[]>([]); const [selected, setSelected] = useState<PageItem | null>(null); const [content, setContent] = useState(''); const [preview, setPreview] = useState(''); const [loading, setLoading] = useState<Record<string, boolean>>({}); const [error, setError] = useState('');
  const setL = (k: string, v: boolean) => setLoading((s) => ({ ...s, [k]: v }));
  async function loadPages() { try { setError(''); const data = await api('/api/pages'); setPages(data.pages || []); } catch (e: any) { setError(e.message); push('error', e.message); } }
  async function openPage(id: string) { if (loading.open) return; setL('open', true); try { const data = await api(`/api/pages/${id}`); setSelected(data.page); setContent(data.content || ''); push('success', '页面加载成功'); } catch (e: any) { push('error', `打开页面失败: ${e.message}`); } finally { setL('open', false); } }
  async function createPage() { if (loading.create) return; setL('create', true); try { const data = await api('/api/pages', { method: 'POST', body: JSON.stringify({ title: '新页面', slug: `new-page-${Date.now()}` }) }); await loadPages(); await openPage(data.page.id); push('success', '页面已创建'); } catch (e: any) { push('error', e.message); } finally { setL('create', false); } }
  async function saveDraft() { if (!selected || loading.save) return; setL('save', true); try { await api(`/api/pages/${selected.id}/draft`, { method: 'POST', body: JSON.stringify({ ...selected, content }) }); push('success', '草稿已保存'); await loadPages(); } catch (e: any) { push('error', `保存失败: ${e.message}`); } finally { setL('save', false); } }
  async function publish() { if (!selected || loading.publish) return; setL('publish', true); try { await api(`/api/pages/${selected.id}/publish`, { method: 'POST', body: JSON.stringify({ ...selected, content }) }); push('success', '页面已发布'); await loadPages(); } catch (e: any) { push('error', `发布失败: ${e.message}`); } finally { setL('publish', false); } }
  async function removePage() { if (!selected || !confirm(`确认删除页面「${selected.title}」？`)) return; setL('delete', true); try { await api(`/api/pages/${selected.id}`, { method: 'DELETE' }); setSelected(null); await loadPages(); push('success', '页面已删除'); } catch (e: any) { push('error', `删除失败: ${e.message}`); } finally { setL('delete', false); } }
  async function updatePreview(next: string) { setContent(next); try { const data = await api('/api/markdown/preview', { method: 'POST', body: JSON.stringify({ markdown: next }) }); setPreview(data.html); } catch {} }
  useEffect(() => { loadPages(); }, []);
  return <div className="grid gap-4 lg:grid-cols-[320px_1fr]"> <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">页面</h2><LoadingButton loading={loading.create} onClick={createPage} className="inline-flex items-center gap-1 rounded-lg bg-[var(--primary)] px-3 py-2 text-xs font-medium text-white"><Plus size={14} />新建</LoadingButton></div>{error && <NetworkError message={error} onRetry={loadPages} />} {!pages.length && !error ? <div className='space-y-2'>{[1,2,3].map(i=><div key={i} className='h-16 animate-pulse rounded bg-slate-100'/>)}</div> : <div className="space-y-2">{pages.map((p) => <button key={p.id} onClick={() => openPage(p.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id === p.id ? 'border-[var(--primary)] bg-[var(--primary-soft)]' : 'border-[var(--border)] hover:border-[var(--primary)]'}`}><div className="text-sm font-medium">{p.title}</div></button>)}</div>}</div>
  <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4">{!selected ? <Empty label="选择或创建一个页面" /> : <div><input value={selected.title} onChange={(e) => setSelected({ ...selected, title: e.target.value })} className="w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2" /><div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="overflow-hidden rounded-xl border border-[var(--border)]"><CodeMirror value={content} height="480px" extensions={[markdown()]} onChange={updatePreview} /></div><div className="max-h-[480px] overflow-auto rounded-xl border border-[var(--border)] bg-[var(--bg)] p-5"><article className="markdown-body" dangerouslySetInnerHTML={{ __html: preview || '<p class="text-sm opacity-60">预览会显示在这里</p>' }} /></div></div>
  <div className="mt-4 flex flex-wrap items-center gap-3"><LoadingButton loading={loading.save} onClick={saveDraft} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2 text-sm"><Save size={16} />保存草稿</LoadingButton><LoadingButton loading={loading.publish} onClick={publish} className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-2 text-sm font-medium text-white"><Send size={16} />发布</LoadingButton><LoadingButton loading={loading.delete} onClick={removePage} className="inline-flex items-center gap-2 rounded-xl border border-rose-400 px-4 py-2 text-sm text-rose-600"><Trash2 size={16} />删除</LoadingButton></div></div>}</div></div>;
}
